name: Lint Check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies, Clean, Build, and Lint
        run: |
          npm install
          rm -rf node_modules/.cache
          rm -rf dist
          npm run build
          npm run lint